load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "observer_pattern",
    srcs = ["observer_pattern.py"],
)

py_test(
    name = "property_observer",
    srcs = ["property_observer.py"],
)

py_test(
    name = "property_dependencies",
    srcs = ["property_dependencies.py"],
)
