load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "builder_pattern",
    srcs = ["builder_pattern.py"],
)

py_test(
    name = "builder_facets",
    srcs = ["builder_facets.py"],
)

py_test(
    name = "builder_inheritance",
    srcs = ["builder_inheritance.py"],
)
