load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "simple_singleton",
    srcs = ["simple_singleton.py"],
)

py_test(
    name = "singleton_decorator",
    srcs = ["singleton_decorator.py"],
)

py_test(
    name = "singleton_metaclass",
    srcs = ["singleton_metaclass.py"],
)
