load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "adapter_pattern",
    srcs = ["adapter_pattern.py"],
)

py_test(
    name = "adapter_pattern_with_caching",
    srcs = ["adapter_pattern_with_caching.py"],
)
