load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "factory_pattern",
    srcs = ["factory_pattern.py"],
)

py_test(
    name = "abstract_factory",
    srcs = ["abstract_factory.py"],
)
