load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "factory_exercise",
    srcs = ["factory_exercise.py"],
)

py_test(
    name = "builder_exercise",
    srcs = ["builder_exercise.py"],
)
