load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "single_responsibility_principle",
    srcs = ["single_responsibility_principle.py"],
)

py_test(
    name = "open_close_principle",
    srcs = ["open_close_principle.py"],
)

py_test(
    name = "liskov_substitution_principle",
    srcs = ["liskov_substitution_principle.py"],
)
