load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "single_responsibility_principle",
    srcs = ["single_responsibility_principle.py"],
)

py_binary(
    name = "open_close_principle",
    srcs = ["open_close_principle.py"],
)
