load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "adapter_exercise",
    srcs = ["adapter_exercise.py"],
)

py_test(
    name = "bridge_exercise",
    srcs = ["bridge_exercise.py"],
)

py_test(
    name = "facade_exercise",
    srcs = ["facade_exercise.py"],
)
