load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "prototype_pattern",
    srcs = ["prototype_pattern.py"],
)

py_test(
    name = "prototype_factory",
    srcs = ["prototype_factory.py"],
)
